name: Test Hugo site

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
      - name: Build site
        run: hugo --gc --minify
